### PR TITLE
Add recycler view to MainActivity to save all your notes

### PR DESCRIPTION
**Pull request by deepakkumardk**
A whole new interface and mechanism to save notes in the form of recycler view

### CODE REVIEW

**Comment by deepakkumardk** [comment]
@hakkikaancaliskan Here's the final commit now you can tag it and release the version. If anything is missing just inform me.
For apk file [check out here](https://drive.google.com/file/d/106jz_hDi8-a2n1eTKVDtkp41qfV8z-tI/view?usp=sharing)

**Comment by hakkikaancaliskan** [comment]
I've found a bug :) will tell you when I get home.

**Comment by deepakkumardk** [comment]
Ya, I see that. My bad, I totally missed that.
Hang on working on it.

**Comment by deepakkumardk** [comment]
Check out [this](https://drive.google.com/file/d/1o3duKXxNa5tCiIxAwfppXgP9p7yJJYEP/view?usp=sharing)

**Comment by hakkikaancaliskan** [comment]
Great :)
I'm merging this.
Texts should be translated (also if you want to add Indian, make a pr).
Also note title should be thick.
I will add them later but if you want to do them, of course you can.

**Comment by hakkikaancaliskan** [comment]
After them I will release a new version 1.4

**Comment by deepakkumardk** [comment]
Yup, translate all the text including in the alert and in the xml files.

**Pull request merged**
