### PR TITLE
Add repository & activities for new and update note

### PR DESCRIPTION
**Pull request by deepakkumardk**

### CODE REVIEW

**Comment by hakkikaancaliskan** [comment]
You doesn't starting newNoteActivity, updateNoteActivity from anywhere and there is nothing to show notes. Why didn't you start this activities from anywhere?

**Comment by deepakkumardk** [comment]
Yes, I will do it after setting the recyclerview in the MainActivity. Hold on until now I havn't changed any interface to the original app, I am building all the blocks one by one, when it will be complete I will just put this complete block to the app.
Sorry, for the delay.

**Comment by hakkikaancaliskan** [comment]
Ok then :) do all your work in this pr. I think no need for other prs. Good luck for you.

**Comment by deepakkumardk** [comment]
Ya, I also think this will be last PR and also I am just following the standards that **make your PR samll**

**Comment by hakkikaancaliskan** [comment]
Merged man :)

**Pull request merged**
