### PR TITLE
Add showcase for Empty RecyclerView

### PR DESCRIPTION
**Pull request by deepakkumardk**

### CODE REVIEW

**Comment by hakkikaancaliskan** [comment]
screenshot_20181006-105725
What you think about this? I think no need for icon also it's low quality.

**Comment by deepakkumardk** [comment]
I think we should use some icon, if you don't want to use the app icon use something else like empty box...

**Comment by deepakkumardk** [comment]
or just use the note icon provided by the android studio, vector asset.

**Comment by hakkikaancaliskan** [comment]
I will take a look :)

**Comment by hakkikaancaliskan** [comment]
screenshot 6 eki 2018 15_04_54
How is this?

**Comment by deepakkumardk** [comment]
nice, circular image of pen would be better :)

**Pull request merged**
